### ISSUE TITLE
Can not find the second item in nested group

### ISSUE THREAD

**Issue by Dushistov** [racer-rust/racer#906]
I use racer 2.1.0.

I created simple crate,
**Cargo.toml**
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Rust Example <rust-snippet@example.com>"]

[dependencies]
spade = "1.5.1"
```
**src/main.rs**
```Rust
extern crate spade;

use spade::{rtree::RTree, PointN};
//use spade::PointN;

fn main() {}
```

If in line `use spade::{rtree::RTree, PointN};` move cursor to `PointN` and execute
`M-x racer-find-definition` it prints "No definition found",
but it works for `rtree::RTree` and also if comment nested group line and uncomment
`use spade::PointN;` line, then it jump to `PointN` without problem.
