### ISSUE TITLE
racer got lost after reqwest::timeout

### ISSUE THREAD

**Issue by Dushistov** [racer-rust/racer#909]
Bellow the most simple example as I can create.
`racer` can find (`racer-find-definition`) `Client`, `builder`,
`timeout`, `Duration`, but `build` it can not find.
`timeout` looks like this:
```Rust
    pub fn timeout<T>(&mut self, timeout: T) -> &mut ClientBuilder
    where T: Into<Option<Duration>>,
```
`racer` can find `ClientBuilder`, if put cursor to `ClientBulder` in `timeout` definition,
also if I create `CliendBuilder` manually it can find `build` method:
```Rust
    let mut builder = reqwest::ClientBuilder::new();
    builder.build().unwrap();
```

but for some reason if put this together it can not find  `reqwest::ClientBuilder::build` method.
  

```Rust
extern crate reqwest;

use std::time::Duration;

fn main() {
    let client = reqwest::Client::builder()
        .timeout(Some(Duration::from_secs(30)))
        .build()
        .unwrap();
}
```
```toml
[package]
name = "foo"
version = "0.1.0"
authors = ["Rust Example <rust-snippet@example.com>"]

[dependencies]
reqwest = "0.8.6"
```
